services:
  # FastAPI Backend - Native Python deployment (simpler than Docker)
  - type: web
    name: terralink-portal-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --workers 2 --bind 0.0.0.0:$PORT"
    rootDir: backend
    envVars:
      # Core Settings
      - key: PROJECT_NAME
        value: TerraLink Portal API
      - key: VERSION
        value: "1.0.0"
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0

      # Security - Generate these in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

      # Google OAuth - Add in Render dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

      # Database - Automatically connected
      - key: DATABASE_URL
        fromDatabase:
          name: terralink-db
          property: connectionString

      # Redis - Disabled for now (using PostgreSQL for sessions)
      # - key: REDIS_URL
      #   fromService:
      #     name: terralink-redis
      #     type: redis
      #     property: connectionString
      - key: USE_REDIS_SESSIONS
        value: false

      # CORS - Update with your Vercel URL (comma-separated)
      - key: ALLOWED_ORIGINS
        value: 'https://terralink-portal.vercel.app,https://portal.terralink.cl'

      # Frontend URL for OAuth redirects
      - key: FRONTEND_URL
        value: 'https://terralink-portal.vercel.app'

      # Cookie Settings
      - key: COOKIE_NAME
        value: terralink_session
      - key: COOKIE_DOMAIN
        sync: false  # Set in dashboard based on your domain
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_HTTPONLY
        value: true
      - key: COOKIE_SAMESITE
        value: lax
      - key: COOKIE_MAX_AGE
        value: 2592000

      # Access Control (comma-separated)
      - key: ALLOWED_DOMAINS
        value: 'terralink.cl,gmail.com'
      - key: ADMIN_EMAILS
        value: 'admin@terralink.cl'

      # Rate Limiting
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 60

      # Logging
      - key: LOG_LEVEL
        value: INFO

# PostgreSQL Database
databases:
  - name: terralink-db
    databaseName: terralink_portal
    user: terralink
    plan: starter # or 'standard' for production